version: '3.5'

networks:
  network_api_clientes:
    driver: bridge

volumes:
  volume_postgres:
  volume_pgadmin: 

services:

    service_postgres:
        container_name: cnt-postgressql
        image: postgres:alpine
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - volume_postgres:/var/lib/postgresql/data
            - ./init.sql :/docker-entrypoint-initdb.d/init.sql
        networks:
            - network_api_clientes
        environment:
            POSTGRES_DB: api_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            CONFIGS: "listen_addresses:'*'"

    service_pgadmin:
        container_name: cnt-pgadmin
        image: dpage/pgadmin4
        ports:
            - '16543:80'
        volumes:
            - 'volume_pgadmin:/root/.pgadmin'
        networks:
            - network_api_clientes
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-admin}'
            PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-admin}'
        depends_on:
            - service_postgres
        restart: unless-stopped

    service_api_clientes:
        container_name: cnt-api
        image: 'api_clientes:latest'
        links:
            - service_postgres
        depends_on:
            - service_postgres
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:80'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - 'DB_CONNECTION_STRING="User ID=postgres; Password=postgres; Server=service_postgres; Port=5432; Database=api_db; Integrated Security=true; Pooling=true;"'
        networks:
            - network_api_clientes

    service_web:
        container_name: cnt-web
        image: 'nginx:alpine'
        ports:
            - '80:80'
        restart: always
        networks:
            - network_api_clientes
        links:
            - service_api_clientes:service_api_clientes
        depends_on:
            - service_api_clientes
        volumes:
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
            - './:/usr/share/nginx/html'
